# Generated by Django 4.2.7 on 2025-12-27 22:35

from django.db import migrations, models
import logistics.models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_align_superuser_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(default=logistics.models._random_code, editable=False, max_length=50, unique=True),
        ),
    ]
