# Generated by Django 4.2.7 on 2025-12-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_client_company_name_client_country_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
