# Generated by Django 4.2.7 on 2025-12-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_alter_client_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loading',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
