# Generated by Django 4.2.7 on 2025-12-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_alter_loading_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerreturn',
            name='container_size',
            field=models.CharField(blank=True, choices=[('20ft', '20 FT Standard'), ('40ft', '40 FT Standard'), ('40ft_hc', '40 FT High Cube'), ('45ft', '45 FT High Cube'), ('lcl', 'LCL / Palletized'), ('other', 'Custom / Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='loading',
            name='container_size',
            field=models.CharField(blank=True, choices=[('20ft', '20 FT Standard'), ('40ft', '40 FT Standard'), ('40ft_hc', '40 FT High Cube'), ('45ft', '45 FT High Cube'), ('lcl', 'LCL / Palletized'), ('other', 'Custom / Other')], max_length=20),
        ),
    ]
