# Generated by Django 4.2.7 on 2026-01-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_containerreturn_container_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transit',
            name='loading',
        ),
        migrations.RemoveField(
            model_name='transit',
            name='vessel_name',
        ),
        migrations.AddField(
            model_name='transit',
            name='container_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transit',
            name='eta_mombasa',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transit',
            name='shipping_line',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
