# Generated by Django 4.2.7 on 2026-01-06 21:05

from django.db import migrations, models


def forwards_copy_eta(apps, schema_editor):
    Transit = apps.get_model('logistics', 'Transit')
    for transit in Transit.objects.all():
        eta_kampala = getattr(transit, 'eta_kampala', None)
        eta_mombasa = getattr(transit, 'eta_mombasa', None)

        if transit.eta is None:
            if eta_kampala is not None:
                transit.eta_location = transit.eta_location or 'kampala'
                transit.eta = eta_kampala
            elif eta_mombasa is not None:
                transit.eta_location = transit.eta_location or 'mombasa'
                transit.eta = eta_mombasa

        if eta_kampala is not None and eta_mombasa is not None and eta_kampala != eta_mombasa:
            remarks = (transit.remarks or '').strip()
            note = f"ETA Mombasa: {eta_mombasa.isoformat(sep=' ', timespec='minutes')}"
            if note not in remarks:
                transit.remarks = f"{remarks}\n{note}".strip() if remarks else note

        transit.save(update_fields=['eta_location', 'eta', 'remarks'])


def backwards_restore_eta_fields(apps, schema_editor):
    # No-op: old fields will be removed, so we can't restore them.
    return


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_remove_transit_loading_remove_transit_vessel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transit',
            name='eta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transit',
            name='eta_location',
            field=models.CharField(blank=True, choices=[('kampala', 'Kampala'), ('mombasa', 'Mombasa')], max_length=20),
        ),
        migrations.RunPython(forwards_copy_eta, backwards_restore_eta_fields),
        migrations.RemoveField(
            model_name='transit',
            name='eta_kampala',
        ),
        migrations.RemoveField(
            model_name='transit',
            name='eta_mombasa',
        ),
    ]
