# Generated by Django 4.2.7 on 2026-01-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0011_remove_transit_eta_kampala_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loading',
            name='loading_id',
        ),
        migrations.AddField(
            model_name='loading',
            name='flow_type',
            field=models.CharField(choices=[('lcl', 'LCL (Less Container Load)'), ('fcl', 'FCL (Full Container Load)')], default='fcl', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='rate_per_cbm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='rate_per_container',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
