# Generated by Django 4.2.7 on 2026-01-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0012_remove_loading_loading_id_loading_flow_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loading',
            name='item_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
