# Generated by Django 4.2.7 on 2026-01-06 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0013_alter_loading_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='document_handling_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
    ]
