# Generated by Django 4.2.7 on 2026-01-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0014_payment_document_handling_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank', 'Bank'), ('mobile_money', 'Mobile Money'), ('cheque', 'Cheque')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('mobile_money', 'Mobile Money'), ('cheque', 'Cheque')], max_length=20),
        ),
    ]
