# Generated by Django 4.2.7 on 2026-01-06 22:28

from django.db import migrations


def normalize_payment_methods(apps, schema_editor):
    Payment = apps.get_model('logistics', 'Payment')
    PaymentTransaction = apps.get_model('logistics', 'PaymentTransaction')

    # Normalize legacy values to the new allowed set:
    # - bank_transfer -> bank
    # - other -> cash
    Payment.objects.filter(payment_method='bank_transfer').update(payment_method='bank')
    Payment.objects.filter(payment_method='other').update(payment_method='cash')

    PaymentTransaction.objects.filter(payment_method='bank_transfer').update(payment_method='bank')
    PaymentTransaction.objects.filter(payment_method='other').update(payment_method='cash')


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0015_alter_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_payment_methods, migrations.RunPython.noop),
    ]
