# Generated by Django 4.2.7 on 2026-01-06 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0016_normalize_payment_methods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='model_type',
            field=models.CharField(choices=[('client', 'Client'), ('loading', 'Loading'), ('transit', 'Transit'), ('quote', 'Quotation'), ('payment', 'Payment'), ('container_return', 'Container Return'), ('user', 'User')], max_length=50),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_cbm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rate_per_container', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('document_handling_fee', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('amount_quoted', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('converted', 'Converted to Invoice')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_quotes', to=settings.AUTH_USER_MODEL)),
                ('loading', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='logistics.loading')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
