# Generated by Django 4.2.7 on 2026-01-06 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0017_alter_auditlog_model_type_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='cbm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='logistics.client'),
        ),
        migrations.AddField(
            model_name='quote',
            name='container_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='container_size',
            field=models.CharField(blank=True, choices=[('20ft', '20 FT Standard'), ('40ft', '40 FT Standard'), ('40ft_hc', '40 FT High Cube'), ('45ft', '45 FT High Cube'), ('lcl', 'LCL / Palletized'), ('other', 'Custom / Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='flow_type',
            field=models.CharField(choices=[('lcl', 'LCL (Less Container Load)'), ('fcl', 'FCL (Full Container Load)')], default='fcl', max_length=10),
        ),
        migrations.AddField(
            model_name='quote',
            name='item_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='loading_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='origin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='loading',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote', to='logistics.loading'),
        ),
    ]
