# Generated by GitHub Copilot on 2026-01-06

from django.db import migrations


def forwards(apps, schema_editor):
    Quote = apps.get_model('logistics', 'Quote')

    for quote in Quote.objects.select_related('loading').all():
        loading = getattr(quote, 'loading', None)
        if not loading:
            continue

        changed = False

        if quote.client_id is None:
            quote.client_id = loading.client_id
            changed = True

        if not quote.container_number:
            quote.container_number = loading.container_number
            changed = True

        if not quote.container_size and getattr(loading, 'container_size', None):
            quote.container_size = loading.container_size
            changed = True

        if not quote.origin:
            quote.origin = loading.origin
            changed = True

        if not quote.destination:
            quote.destination = loading.destination
            changed = True

        if quote.loading_date is None:
            quote.loading_date = loading.loading_date
            changed = True

        if quote.item_description is None and loading.item_description is not None:
            quote.item_description = loading.item_description
            changed = True

        if getattr(quote, 'flow_type', None) != getattr(loading, 'flow_type', None):
            quote.flow_type = loading.flow_type
            changed = True

        # LCL only: store CBM from cargo record (Loading.weight)
        if quote.cbm is None and loading.weight is not None:
            quote.cbm = loading.weight
            changed = True

        if changed:
            quote.save(update_fields=[
                'client',
                'container_number',
                'container_size',
                'origin',
                'destination',
                'loading_date',
                'item_description',
                'flow_type',
                'cbm',
            ])


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0018_quote_cbm_quote_client_quote_container_number_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
