# Generated by Django 4.2.7 on 2026-06-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0022_merge_0020_alter_customuser_role_0021_customuser_permission_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='loading',
            name='cargo_type',
            field=models.CharField(choices=[('air_cargo', 'Air Cargo'), ('freight_cargo', 'Freight Cargo')], default='freight_cargo', max_length=20),
        ),
        migrations.AddField(
            model_name='loading',
            name='ctns',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='CTNs'),
        ),
        migrations.AlterField(
            model_name='loading',
            name='container_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
