# Generated by Django 4.2.7 on 2026-07-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0023_loading_cargo_type_ctns"),
    ]

    operations = [
        migrations.AddField(
            model_name="loading",
            name="airline",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="loading",
            name="handling_fees",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="loading",
            name="item_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="loading",
            name="rate_per_carton",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="loading",
            name="size_per_carton",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="loading",
            name="origin",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
