# Generated by Django 4.2.7 on 2026-07-01

from decimal import Decimal

from django.db import migrations, models


def copy_air_cargo_weight(apps, schema_editor):
    Loading = apps.get_model("logistics", "Loading")
    Loading.objects.filter(cargo_type="air_cargo", gross_weight__isnull=True).update(
        gross_weight=models.F("weight")
    )


def recalculate_air_cargo_payments(apps, schema_editor):
    Payment = apps.get_model("logistics", "Payment")
    payments = Payment.objects.select_related("loading").filter(
        loading__cargo_type="air_cargo",
        loading__gross_weight__isnull=False,
        loading__rate_per_kg__isnull=False,
    )
    for payment in payments.iterator():
        loading = payment.loading
        amount_charged = (loading.gross_weight * loading.rate_per_kg) + (
            loading.handling_fees or Decimal("0")
        )
        amount_paid = payment.amount_paid or Decimal("0")
        Payment.objects.filter(pk=payment.pk).update(
            amount_charged=amount_charged,
            balance=amount_charged - amount_paid,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0024_air_cargo_loading_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loading",
            old_name="rate_per_carton",
            new_name="rate_per_kg",
        ),
        migrations.AddField(
            model_name="loading",
            name="gross_weight",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.RunPython(copy_air_cargo_weight, migrations.RunPython.noop),
        migrations.RunPython(recalculate_air_cargo_payments, migrations.RunPython.noop),
    ]
