# Generated by GitHub Copilot on 2026-08-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0025_air_cargo_gross_weight_rate_per_kg"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="pvoc_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12
            ),
        ),
    ]
