# Generated by GitHub Copilot on 2026-08-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0026_payment_pvoc_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="cargo_type",
            field=models.CharField(
                choices=[
                    ("air_cargo", "Air Cargo"),
                    ("freight_cargo", "Freight Cargo"),
                ],
                default="freight_cargo",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="item_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="quote",
            name="ctns",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="CTNs"
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="gross_weight",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="rate_per_kg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="handling_fees",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="airline",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="quote",
            name="size_per_carton",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
