# Generated by GitHub Copilot on 2026-08-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0027_quote_air_cargo_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="pvoc_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12
            ),
        ),
    ]
