# Generated by Django 4.2.8 on 2026-08-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0030_cargo_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loading',
            name='cargo_unit',
            field=models.CharField(blank=True, choices=[('ctn', 'CTNs'), ('package', 'Packages'), ('parcel', 'Parcels'), ('pack', 'Packs'), ('set', 'Sets'), ('other', 'Other')], default='ctn', max_length=20),
        ),
        migrations.AlterField(
            model_name='quote',
            name='cargo_unit',
            field=models.CharField(blank=True, choices=[('ctn', 'CTNs'), ('package', 'Packages'), ('parcel', 'Parcels'), ('pack', 'Packs'), ('set', 'Sets'), ('other', 'Other')], default='ctn', max_length=20),
        ),
    ]
