# Generated by Django 4.2.8 on 2026-08-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0031_alter_loading_cargo_unit_alter_quote_cargo_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='loading',
            name='air_rate_basis',
            field=models.CharField(blank=True, choices=[('package', 'Package Type'), ('kg', 'KGS')], default='package', max_length=20),
        ),
        migrations.AddField(
            model_name='quote',
            name='air_rate_basis',
            field=models.CharField(blank=True, choices=[('package', 'Package Type'), ('kg', 'KGS')], default='package', max_length=20),
        ),
    ]
