# Generated by Django 5.2.15 on 2026-08-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0034_loading_currency_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD - US Dollar'), ('UGX', 'UGX - Ugandan Shilling')], default='USD', max_length=10),
        ),
    ]
