# Generated by Django 4.2.8 on 2026-08-21 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0035_alter_quote_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteContainerLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('container_size', models.CharField(choices=[('20ft', '20 FT Standard'), ('40ft', '40 FT Standard'), ('40ft_hc', '40 FT High Cube'), ('45ft', '45 FT High Cube'), ('lcl', 'LCL / Palletized'), ('other', 'Custom / Other')], max_length=20)),
                ('rate_per_container', models.DecimalField(decimal_places=2, max_digits=12)),
                ('container_numbers', models.TextField(blank=True)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_lines', to='logistics.quote')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='LoadingContainerLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('container_size', models.CharField(choices=[('20ft', '20 FT Standard'), ('40ft', '40 FT Standard'), ('40ft_hc', '40 FT High Cube'), ('45ft', '45 FT High Cube'), ('lcl', 'LCL / Palletized'), ('other', 'Custom / Other')], max_length=20)),
                ('rate_per_container', models.DecimalField(decimal_places=2, max_digits=12)),
                ('container_numbers', models.TextField(blank=True)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_lines', to='logistics.loading')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
